apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        command: ['sh', '-c']
        args:
        - while true 
            echo "$(date) INFO some app data" > /var/sidecar/myapp.log;
            sleep 5;
          done
      - name: log-sidecar
        image: busybox:1.36
        command: ['sh', '-c']
        args:
        - tail -f /var/sidecar/myapp.log
        volumeMounts:
          - name: log-data
            mountPath: /var/sidecar
      volumes:
        - name: log-data
          emptyDir: {}
        
