apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-pv
spec:
  hostPath:
    path: "/mnt/data"
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Delete
  # storageClassName: local-storage
  accessModes:
  - ReadWriteMany