apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: dev-cr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulSets
  verbs:
  - get
  - list
  - create
